#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <pid>"
    exit 1
fi

arr=("$1" 0)

while [ ${#arr[@]} -gt 0 ]; do

    # remove last element
    space=${arr[${#arr[@]}-1]}
    unset arr[${#arr[@]}-1]
    pid=${arr[${#arr[@]}-1]}
    unset arr[${#arr[@]}-1]

    # name of process
    name=`ps -p $pid -o comm=`

    if [ ! -d "/proc/$pid" ]; then
        continue
    fi

    mem=`cat /proc/$pid/status | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} VmRSS | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} -o '[0-9]\+' | awk '{print $1/1024 " MB"}'`
    printf "%${space}s$name($pid): $mem\n"

    # get children
    children=`pgrep -P $pid`

    # add children to array
    for child in $children; do
        arr+=("$child" $((space+2)))
    done
done
