#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <pid>"
    exit 1
fi

declare -a arr
arr=("$1" 0)

while [ ${#arr[@]} -gt 0 ]; do

    # remove last element
    space=${arr[${#arr[@]}-1]}
    unset arr[${#arr[@]}-1]
    pid=${arr[${#arr[@]}-1]}
    unset arr[${#arr[@]}-1]

    [ -d "/proc/$pid" ] || continue

    GREP_OPTS=${GREP_OPTS:-"
      --color=auto
      --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}
      "}
    mem=$(grep $GREP_OPTS VmRSS /proc/$pid/status \
      | grep $GREP_OPTS -o '[0-9]\+' \
      | awk '{print $1/1024 " MB"}')

    # name of process
    name=$(ps -p $pid -o comm=)

    printf "%${space}s%s($pid): $mem\n" '' "$name"

    # get children
    children=$(pgrep -P $pid)

    # add children to array
    for child in $children; do
        arr+=("$child" $((space+2)))
    done
done
